backend:
  name: github
  repo: xinapess-cmd/klaproject
  branch: main
  base_url: https://klaprojects.net
  auth_endpoint: admin/

media_folder: "images"
public_folder: "/images"

collections:
  - name: "projets"
    label: "Projets"
    folder: "data/projets"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre", name: "titre", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
